export type AssetItem = { ticker: string; name: string; type: string; exchange: string; };

export const TRENDING: AssetItem[] = [
  // US Large Cap
  {ticker:"AAPL",name:"Apple Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"MSFT",name:"Microsoft Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NVDA",name:"NVIDIA Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"TSLA",name:"Tesla Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"AMZN",name:"Amazon.com",type:"EQUITY",exchange:"NMS"},
  {ticker:"META",name:"Meta Platforms",type:"EQUITY",exchange:"NMS"},
  {ticker:"GOOGL",name:"Alphabet Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"GOOG",name:"Alphabet Inc. C",type:"EQUITY",exchange:"NMS"},
  {ticker:"JPM",name:"JPMorgan Chase",type:"EQUITY",exchange:"NYQ"},
  {ticker:"V",name:"Visa Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MA",name:"Mastercard",type:"EQUITY",exchange:"NYQ"},
  {ticker:"JNJ",name:"Johnson & Johnson",type:"EQUITY",exchange:"NYQ"},
  {ticker:"WMT",name:"Walmart Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BAC",name:"Bank of America",type:"EQUITY",exchange:"NYQ"},
  {ticker:"XOM",name:"ExxonMobil",type:"EQUITY",exchange:"NYQ"},
  {ticker:"UNH",name:"UnitedHealth Group",type:"EQUITY",exchange:"NYQ"},
  {ticker:"PG",name:"Procter & Gamble",type:"EQUITY",exchange:"NYQ"},
  {ticker:"HD",name:"Home Depot",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ABBV",name:"AbbVie Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MRK",name:"Merck & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"AVGO",name:"Broadcom Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"COST",name:"Costco Wholesale",type:"EQUITY",exchange:"NMS"},
  {ticker:"KO",name:"Coca-Cola Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"LLY",name:"Eli Lilly & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MCD",name:"McDonald's Corp.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"INTC",name:"Intel Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"AMD",name:"Advanced Micro Devices",type:"EQUITY",exchange:"NMS"},
  {ticker:"CRM",name:"Salesforce Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ADBE",name:"Adobe Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NFLX",name:"Netflix Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"PYPL",name:"PayPal Holdings",type:"EQUITY",exchange:"NMS"},
  {ticker:"QCOM",name:"Qualcomm Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"TXN",name:"Texas Instruments",type:"EQUITY",exchange:"NMS"},
  {ticker:"HON",name:"Honeywell Intl.",type:"EQUITY",exchange:"NMS"},
  {ticker:"UPS",name:"United Parcel Service",type:"EQUITY",exchange:"NYQ"},
  {ticker:"CAT",name:"Caterpillar Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"GS",name:"Goldman Sachs",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MS",name:"Morgan Stanley",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BLK",name:"BlackRock Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SPGI",name:"S&P Global",type:"EQUITY",exchange:"NYQ"},
  {ticker:"RTX",name:"Raytheon Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BA",name:"Boeing Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"LMT",name:"Lockheed Martin",type:"EQUITY",exchange:"NYQ"},
  {ticker:"GE",name:"General Electric",type:"EQUITY",exchange:"NYQ"},
  {ticker:"DE",name:"Deere & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"DIS",name:"Walt Disney Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SBUX",name:"Starbucks Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NKE",name:"Nike Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"CVX",name:"Chevron Corp.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"NOW",name:"ServiceNow Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"UBER",name:"Uber Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ABNB",name:"Airbnb Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"COIN",name:"Coinbase Global",type:"EQUITY",exchange:"NMS"},
  {ticker:"PLTR",name:"Palantir Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ARM",name:"Arm Holdings",type:"EQUITY",exchange:"NMS"},
  {ticker:"SMCI",name:"Super Micro Computer",type:"EQUITY",exchange:"NMS"},
  // Europe
  {ticker:"MC.PA",name:"LVMH",type:"EQUITY",exchange:"PAR"},
  {ticker:"TTE.PA",name:"TotalEnergies",type:"EQUITY",exchange:"PAR"},
  {ticker:"ASML",name:"ASML Holding",type:"EQUITY",exchange:"NMS"},
  {ticker:"SAP",name:"SAP SE",type:"EQUITY",exchange:"NYQ"},
  {ticker:"OR.PA",name:"L'Oréal",type:"EQUITY",exchange:"PAR"},
  {ticker:"SAN.PA",name:"Sanofi",type:"EQUITY",exchange:"PAR"},
  {ticker:"AIR.PA",name:"Airbus SE",type:"EQUITY",exchange:"PAR"},
  {ticker:"BNP.PA",name:"BNP Paribas",type:"EQUITY",exchange:"PAR"},
  {ticker:"SU.PA",name:"Schneider Electric",type:"EQUITY",exchange:"PAR"},
  {ticker:"AI.PA",name:"Air Liquide",type:"EQUITY",exchange:"PAR"},
  {ticker:"KER.PA",name:"Kering",type:"EQUITY",exchange:"PAR"},
  {ticker:"HO.PA",name:"Thales",type:"EQUITY",exchange:"PAR"},
  {ticker:"DG.PA",name:"Vinci SA",type:"EQUITY",exchange:"PAR"},
  {ticker:"CS.PA",name:"AXA SA",type:"EQUITY",exchange:"PAR"},
  {ticker:"ACA.PA",name:"Crédit Agricole",type:"EQUITY",exchange:"PAR"},
  {ticker:"GLE.PA",name:"Société Générale",type:"EQUITY",exchange:"PAR"},
  {ticker:"STLA",name:"Stellantis NV",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SIE.DE",name:"Siemens AG",type:"EQUITY",exchange:"GER"},
  {ticker:"ALV.DE",name:"Allianz SE",type:"EQUITY",exchange:"GER"},
  {ticker:"BMW.DE",name:"BMW AG",type:"EQUITY",exchange:"GER"},
  {ticker:"VOW3.DE",name:"Volkswagen AG",type:"EQUITY",exchange:"GER"},
  {ticker:"BAYN.DE",name:"Bayer AG",type:"EQUITY",exchange:"GER"},
  {ticker:"BAS.DE",name:"BASF SE",type:"EQUITY",exchange:"GER"},
  {ticker:"DTE.DE",name:"Deutsche Telekom",type:"EQUITY",exchange:"GER"},
  {ticker:"ADS.DE",name:"Adidas AG",type:"EQUITY",exchange:"GER"},
  {ticker:"HSBA.L",name:"HSBC Holdings",type:"EQUITY",exchange:"LSE"},
  {ticker:"BP.L",name:"BP PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"GSK.L",name:"GSK PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"SHEL.L",name:"Shell PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"RIO.L",name:"Rio Tinto",type:"EQUITY",exchange:"LSE"},
  {ticker:"NOVN.SW",name:"Novartis AG",type:"EQUITY",exchange:"EBS"},
  {ticker:"NESN.SW",name:"Nestlé SA",type:"EQUITY",exchange:"EBS"},
  {ticker:"RO.SW",name:"Roche Holding",type:"EQUITY",exchange:"EBS"},
  // Asia
  {ticker:"TSM",name:"Taiwan Semiconductor",type:"EQUITY",exchange:"NYQ"},
  {ticker:"7203.T",name:"Toyota Motor",type:"EQUITY",exchange:""},
  {ticker:"6758.T",name:"Sony Group",type:"EQUITY",exchange:""},
  {ticker:"9984.T",name:"SoftBank Group",type:"EQUITY",exchange:""},
  {ticker:"BABA",name:"Alibaba Group",type:"EQUITY",exchange:"NYQ"},
  {ticker:"TCEHY",name:"Tencent Holdings",type:"EQUITY",exchange:""},
  {ticker:"005930.KS",name:"Samsung Electronics",type:"EQUITY",exchange:""},
  // ETF
  {ticker:"SPY",name:"SPDR S&P 500 ETF",type:"ETF",exchange:"NYSEArca"},
  {ticker:"QQQ",name:"Invesco QQQ Trust",type:"ETF",exchange:"NMS"},
  {ticker:"VTI",name:"Vanguard Total Market",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VEA",name:"Vanguard Dev. Markets",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VWO",name:"Vanguard FTSE EM",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EEM",name:"iShares MSCI EM",type:"ETF",exchange:"NYSEArca"},
  {ticker:"GLD",name:"SPDR Gold Shares",type:"ETF",exchange:"NYSEArca"},
  {ticker:"SLV",name:"iShares Silver Trust",type:"ETF",exchange:"NYSEArca"},
  {ticker:"IWM",name:"iShares Russell 2000",type:"ETF",exchange:"NYSEArca"},
  {ticker:"ARKK",name:"ARK Innovation ETF",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLF",name:"Financial Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLK",name:"Technology Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLE",name:"Energy Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLV",name:"Health Care Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLI",name:"Industrial Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"IBIT",name:"iShares Bitcoin Trust",type:"ETF",exchange:"NMS"},
  {ticker:"FBTC",name:"Fidelity Wise Origin Bitcoin",type:"ETF",exchange:"NMS"},
  {ticker:"CW8.PA",name:"Amundi MSCI World",type:"ETF",exchange:"PAR"},
  {ticker:"EWLD.PA",name:"Lyxor MSCI World",type:"ETF",exchange:"PAR"},
  {ticker:"ESE.PA",name:"BNP Paribas Easy S&P 500",type:"ETF",exchange:"PAR"},
  {ticker:"PANX.PA",name:"Amundi Nasdaq-100",type:"ETF",exchange:"PAR"},
  {ticker:"EWJ",name:"iShares MSCI Japan",type:"ETF",exchange:"NYSEArca"},
  {ticker:"FXI",name:"iShares China Large-Cap",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EWG",name:"iShares MSCI Germany",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EWU",name:"iShares MSCI UK",type:"ETF",exchange:"NYSEArca"},
  {ticker:"ACWI",name:"iShares MSCI ACWI",type:"ETF",exchange:"NMS"},
  {ticker:"AGG",name:"iShares Core US Aggregate",type:"ETF",exchange:"NYSEArca"},
  {ticker:"TLT",name:"iShares 20+ Year Treasury",type:"ETF",exchange:"NMS"},
  {ticker:"HYG",name:"iShares iBoxx High Yield",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VNQ",name:"Vanguard Real Estate ETF",type:"ETF",exchange:"NYSEArca"},
  // Crypto
  {ticker:"BTC-USD",name:"Bitcoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ETH-USD",name:"Ethereum",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"SOL-USD",name:"Solana",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"BNB-USD",name:"BNB",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"XRP-USD",name:"XRP",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"DOGE-USD",name:"Dogecoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ADA-USD",name:"Cardano",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"AVAX-USD",name:"Avalanche",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"DOT-USD",name:"Polkadot",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"INJ-USD",name:"Injective",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"LINK-USD",name:"Chainlink",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"UNI7083-USD",name:"Uniswap",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"LTC-USD",name:"Litecoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ATOM-USD",name:"Cosmos",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"NEAR-USD",name:"NEAR Protocol",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ARB-USD",name:"Arbitrum",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"OP-USD",name:"Optimism",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"SUI20947-USD",name:"Sui",type:"CRYPTOCURRENCY",exchange:""},
  // Indices
  {ticker:"^GSPC",name:"S&P 500",type:"INDEX",exchange:""},
  {ticker:"^NDX",name:"Nasdaq 100",type:"INDEX",exchange:""},
  {ticker:"^DJI",name:"Dow Jones",type:"INDEX",exchange:""},
  {ticker:"^RUT",name:"Russell 2000",type:"INDEX",exchange:""},
  {ticker:"^VIX",name:"VIX Volatility",type:"INDEX",exchange:""},
  {ticker:"^FCHI",name:"CAC 40",type:"INDEX",exchange:""},
  {ticker:"^GDAXI",name:"DAX 40",type:"INDEX",exchange:""},
  {ticker:"^FTSE",name:"FTSE 100",type:"INDEX",exchange:""},
  {ticker:"^N225",name:"Nikkei 225",type:"INDEX",exchange:""},
  {ticker:"^HSI",name:"Hang Seng",type:"INDEX",exchange:""},
  {ticker:"^STOXX50E",name:"Euro Stoxx 50",type:"INDEX",exchange:""},
  {ticker:"^IBEX",name:"IBEX 35",type:"INDEX",exchange:""},
  {ticker:"^AEX",name:"AEX Amsterdam",type:"INDEX",exchange:""},
  {ticker:"^SSMI",name:"SMI Switzerland",type:"INDEX",exchange:""},
];

/**
 * Dominant brand colour per ticker.
 * Used as the default chart line colour when the user hasn't set a custom one.
 * All values are chosen to be legible on the dark terminal background (#041124).
 */
export const BRAND_COLORS: Record<string, string> = {

  // ── US Large Cap ──────────────────────────────────────────────────────────
  AAPL:  "#A8B2C0", MSFT:  "#00A4EF", NVDA:  "#76B900", TSLA:  "#E31937",
  AMZN:  "#FF9900", META:  "#1877F2", GOOGL: "#4285F4", GOOG:  "#4285F4",
  JPM:   "#005EB8", V:     "#3B82C4", MA:    "#FF5F00", JNJ:   "#CC0000",
  WMT:   "#0071CE", BAC:   "#DC1431", XOM:   "#D82718", UNH:   "#0066CC",
  PG:    "#4A90E2", HD:    "#F96302", ABBV:  "#006FAD", MRK:   "#009360",
  AVGO:  "#CF0A2C", COST:  "#E31837", KO:    "#F40009", LLY:   "#D13039",
  MCD:   "#DA291C", INTC:  "#0068B5", AMD:   "#ED1C24", CRM:   "#00A1E0",
  ADBE:  "#FA0F00", NFLX:  "#E50914", PYPL:  "#0070BA", QCOM:  "#3253DC",
  TXN:   "#C00000", HON:   "#C8102E", UPS:   "#8B4513", CAT:   "#CC8A00",
  GS:    "#6DA883", MS:    "#4A7ED9", BLK:   "#3A4F7A", SPGI:  "#4A7ED9",
  RTX:   "#2E5FBF", BA:    "#3A6BC0", LMT:   "#4066C8", GE:    "#3CB6CE",
  DE:    "#367C2B", DIS:   "#006E99", SBUX:  "#00704A", NKE:   "#F05020",
  CVX:   "#0096D6", NOW:   "#00C7B1", UBER:  "#6C6C6C", ABNB:  "#FF385C",
  COIN:  "#0052FF", PLTR:  "#3E7EC4", ARM:   "#0091BD", SMCI:  "#3CB4C8",
  // ── Europe ────────────────────────────────────────────────────────────────
  "MC.PA":   "#C5A87B", "TTE.PA":  "#DA291C", ASML:      "#00A0E9",
  SAP:       "#0FAAFF", "OR.PA":   "#C9B76A", "SAN.PA":  "#9B1B2A",
  "AIR.PA":  "#3056C4", "BNP.PA":  "#009A44", "SU.PA":   "#3DCD58",
  "AI.PA":   "#009FE3", "KER.PA":  "#C8A882", "HO.PA":   "#2E5FBF",
  "DG.PA":   "#007DC4", "CS.PA":   "#3333CC", "ACA.PA":  "#009B3A",
  "GLE.PA":  "#E60028", STLA:      "#1B4AA0", "SIE.DE":  "#009999",
  "ALV.DE":  "#3864C8", "BMW.DE":  "#1C69D4", "VOW3.DE": "#1D5BA0",
  "BAYN.DE": "#00BCFF", "BAS.DE":  "#009540", "DTE.DE":  "#E20074",
  "ADS.DE":  "#C0372A", "HSBA.L":  "#DB0011", "BP.L":    "#009900",
  "GSK.L":   "#F36633", "SHEL.L":  "#FFCC00", "RIO.L":   "#BF1B2C",
  "NOVN.SW": "#EC0016", "NESN.SW": "#C8922A", "RO.SW":   "#0066CC",
  // ── Asia ──────────────────────────────────────────────────────────────────
  TSM:        "#007BCF", "7203.T":    "#EB0A1E", "6758.T":    "#002FA7",
  "9984.T":   "#CC3333", BABA:        "#FF6A00", TCEHY:       "#21A453",
  "005930.KS":"#1428A0",
  // ── ETF ───────────────────────────────────────────────────────────────────
  SPY:  "#3A6BC0", QQQ:  "#4A52A8", VTI:  "#8B1A2E", VEA:  "#8B2244",
  VWO:  "#8B3266", EEM:  "#1A8FD1", GLD:  "#D4AF37", SLV:  "#A8A9AD",
  IWM:  "#1A72C0", ARKK: "#2DDE98", XLF:  "#2E7FBF", XLK:  "#5B7FD3",
  XLE:  "#D4791F", XLV:  "#3DA54E", XLI:  "#5B9BD5", IBIT: "#F7931A",
  FBTC: "#F7931A", "CW8.PA":  "#009FE3", "EWLD.PA": "#1E8FA8",
  "ESE.PA":  "#009FE3", "PANX.PA": "#009FE3", EWJ:  "#1A8FD1",
  FXI:  "#1A8FD1", EWG:  "#1A8FD1", EWU:  "#1A8FD1", ACWI: "#1A8FD1",
  AGG:  "#3A7BC8", TLT:  "#1A72C0", HYG:  "#1A8FD1", VNQ:  "#8B2244",
  // ── Crypto ────────────────────────────────────────────────────────────────
  //
  // Sans entrée ici, la teinte est extraite du logo — ce qui convient à une
  // marque mais mal à une illustration : le pelage du chien de WIF donnait un
  // brun sombre, illisible sur fond noir et sans rapport avec l'identité du
  // jeton.
  "KAS-USD":      "#70C7BA", "WIF-USD":      "#D96F3E", "SHIB-USD":     "#FFA409",
  "PEPE-USD":     "#3D8130", "TON-USD":      "#0098EA", "APT-USD":      "#06B6D4",
  "ICP-USD":      "#29ABE2", "FIL-USD":      "#0090FF", "TRX-USD":      "#EF0027",
  "BCH-USD":      "#8DC351", "MATIC-USD":    "#8247E5",
  "BTC-USD":      "#F7931A", "ETH-USD":      "#627EEA", "SOL-USD":      "#9945FF",
  "BNB-USD":      "#F3BA2F", "XRP-USD":      "#00AAE4", "DOGE-USD":     "#C2A633",
  "ADA-USD":      "#0E70FF", "AVAX-USD":     "#E84142", "DOT-USD":      "#E6007A",
  "INJ-USD":      "#00B2FF", "LINK-USD":     "#2A5ADA", "UNI7083-USD":  "#FF007A",
  "LTC-USD":      "#B0B0B0", "ATOM-USD":     "#8B8FBE", "NEAR-USD":     "#00C08B",
  "ARB-USD":      "#4CC9F0", "OP-USD":       "#FF0420", "SUI20947-USD": "#4DA2FF",
  // ── Indices ───────────────────────────────────────────────────────────────
  "^GSPC":    "#4A7ED9", "^NDX":     "#6A5ACD", "^DJI":     "#3A6BC0",
  "^RUT":     "#7B68EE", "^VIX":     "#CC4444", "^FCHI":    "#3352C0",
  "^GDAXI":   "#CC8A00", "^FTSE":    "#CC0000", "^N225":    "#CC003A",
  "^HSI":     "#CC0000", "^STOXX50E":"#4466CC", "^IBEX":    "#CC1A25",
  "^AEX":     "#FF6600", "^SSMI":    "#CC1A35",
};

/**
 * Nom complet d'un actif, depuis le catalogue ci-dessus.
 *
 * Renvoie null pour un ticker inconnu plutôt qu'un intitulé inventé : la tuile
 * n'affiche alors que le ticker, ce qui vaut mieux qu'une ligne fausse.
 */
const NAME_BY_TICKER: Record<string, string> = Object.fromEntries(
  TRENDING.map(a => [a.ticker, a.name]),
);

export function assetName(ticker: string): string | null {
  return NAME_BY_TICKER[ticker] ?? null;
}
