export type AssetItem = { ticker: string; name: string; type: string; exchange: string; };

export const TRENDING: AssetItem[] = [
  // US Large Cap
  {ticker:"AAPL",name:"Apple Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"MSFT",name:"Microsoft Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NVDA",name:"NVIDIA Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"TSLA",name:"Tesla Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"AMZN",name:"Amazon.com",type:"EQUITY",exchange:"NMS"},
  {ticker:"META",name:"Meta Platforms",type:"EQUITY",exchange:"NMS"},
  {ticker:"GOOGL",name:"Alphabet Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"GOOG",name:"Alphabet Inc. C",type:"EQUITY",exchange:"NMS"},
  {ticker:"JPM",name:"JPMorgan Chase",type:"EQUITY",exchange:"NYQ"},
  {ticker:"V",name:"Visa Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MA",name:"Mastercard",type:"EQUITY",exchange:"NYQ"},
  {ticker:"JNJ",name:"Johnson & Johnson",type:"EQUITY",exchange:"NYQ"},
  {ticker:"WMT",name:"Walmart Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BAC",name:"Bank of America",type:"EQUITY",exchange:"NYQ"},
  {ticker:"XOM",name:"ExxonMobil",type:"EQUITY",exchange:"NYQ"},
  {ticker:"UNH",name:"UnitedHealth Group",type:"EQUITY",exchange:"NYQ"},
  {ticker:"PG",name:"Procter & Gamble",type:"EQUITY",exchange:"NYQ"},
  {ticker:"HD",name:"Home Depot",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ABBV",name:"AbbVie Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MRK",name:"Merck & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"AVGO",name:"Broadcom Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"COST",name:"Costco Wholesale",type:"EQUITY",exchange:"NMS"},
  {ticker:"KO",name:"Coca-Cola Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"LLY",name:"Eli Lilly & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MCD",name:"McDonald's Corp.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"INTC",name:"Intel Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"AMD",name:"Advanced Micro Devices",type:"EQUITY",exchange:"NMS"},
  {ticker:"CRM",name:"Salesforce Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ADBE",name:"Adobe Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NFLX",name:"Netflix Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"PYPL",name:"PayPal Holdings",type:"EQUITY",exchange:"NMS"},
  {ticker:"QCOM",name:"Qualcomm Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"TXN",name:"Texas Instruments",type:"EQUITY",exchange:"NMS"},
  {ticker:"HON",name:"Honeywell Intl.",type:"EQUITY",exchange:"NMS"},
  {ticker:"UPS",name:"United Parcel Service",type:"EQUITY",exchange:"NYQ"},
  {ticker:"CAT",name:"Caterpillar Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"GS",name:"Goldman Sachs",type:"EQUITY",exchange:"NYQ"},
  {ticker:"MS",name:"Morgan Stanley",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BLK",name:"BlackRock Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SPGI",name:"S&P Global",type:"EQUITY",exchange:"NYQ"},
  {ticker:"RTX",name:"Raytheon Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"BA",name:"Boeing Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"LMT",name:"Lockheed Martin",type:"EQUITY",exchange:"NYQ"},
  {ticker:"GE",name:"General Electric",type:"EQUITY",exchange:"NYQ"},
  {ticker:"DE",name:"Deere & Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"DIS",name:"Walt Disney Co.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SBUX",name:"Starbucks Corp.",type:"EQUITY",exchange:"NMS"},
  {ticker:"NKE",name:"Nike Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"CVX",name:"Chevron Corp.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"NOW",name:"ServiceNow Inc.",type:"EQUITY",exchange:"NYQ"},
  {ticker:"UBER",name:"Uber Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ABNB",name:"Airbnb Inc.",type:"EQUITY",exchange:"NMS"},
  {ticker:"COIN",name:"Coinbase Global",type:"EQUITY",exchange:"NMS"},
  {ticker:"PLTR",name:"Palantir Technologies",type:"EQUITY",exchange:"NYQ"},
  {ticker:"ARM",name:"Arm Holdings",type:"EQUITY",exchange:"NMS"},
  {ticker:"SMCI",name:"Super Micro Computer",type:"EQUITY",exchange:"NMS"},
  // Europe
  {ticker:"MC.PA",name:"LVMH",type:"EQUITY",exchange:"PAR"},
  {ticker:"TTE.PA",name:"TotalEnergies",type:"EQUITY",exchange:"PAR"},
  {ticker:"ASML",name:"ASML Holding",type:"EQUITY",exchange:"NMS"},
  {ticker:"SAP",name:"SAP SE",type:"EQUITY",exchange:"NYQ"},
  {ticker:"OR.PA",name:"L'Oréal",type:"EQUITY",exchange:"PAR"},
  {ticker:"SAN.PA",name:"Sanofi",type:"EQUITY",exchange:"PAR"},
  {ticker:"AIR.PA",name:"Airbus SE",type:"EQUITY",exchange:"PAR"},
  {ticker:"BNP.PA",name:"BNP Paribas",type:"EQUITY",exchange:"PAR"},
  {ticker:"SU.PA",name:"Schneider Electric",type:"EQUITY",exchange:"PAR"},
  {ticker:"AI.PA",name:"Air Liquide",type:"EQUITY",exchange:"PAR"},
  {ticker:"KER.PA",name:"Kering",type:"EQUITY",exchange:"PAR"},
  {ticker:"HO.PA",name:"Thales",type:"EQUITY",exchange:"PAR"},
  {ticker:"DG.PA",name:"Vinci SA",type:"EQUITY",exchange:"PAR"},
  {ticker:"CS.PA",name:"AXA SA",type:"EQUITY",exchange:"PAR"},
  {ticker:"ACA.PA",name:"Crédit Agricole",type:"EQUITY",exchange:"PAR"},
  {ticker:"GLE.PA",name:"Société Générale",type:"EQUITY",exchange:"PAR"},
  {ticker:"STLA",name:"Stellantis NV",type:"EQUITY",exchange:"NYQ"},
  {ticker:"SIE.DE",name:"Siemens AG",type:"EQUITY",exchange:"GER"},
  {ticker:"ALV.DE",name:"Allianz SE",type:"EQUITY",exchange:"GER"},
  {ticker:"BMW.DE",name:"BMW AG",type:"EQUITY",exchange:"GER"},
  {ticker:"VOW3.DE",name:"Volkswagen AG",type:"EQUITY",exchange:"GER"},
  {ticker:"BAYN.DE",name:"Bayer AG",type:"EQUITY",exchange:"GER"},
  {ticker:"BAS.DE",name:"BASF SE",type:"EQUITY",exchange:"GER"},
  {ticker:"DTE.DE",name:"Deutsche Telekom",type:"EQUITY",exchange:"GER"},
  {ticker:"ADS.DE",name:"Adidas AG",type:"EQUITY",exchange:"GER"},
  {ticker:"HSBA.L",name:"HSBC Holdings",type:"EQUITY",exchange:"LSE"},
  {ticker:"BP.L",name:"BP PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"GSK.L",name:"GSK PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"SHEL.L",name:"Shell PLC",type:"EQUITY",exchange:"LSE"},
  {ticker:"RIO.L",name:"Rio Tinto",type:"EQUITY",exchange:"LSE"},
  {ticker:"NOVN.SW",name:"Novartis AG",type:"EQUITY",exchange:"EBS"},
  {ticker:"NESN.SW",name:"Nestlé SA",type:"EQUITY",exchange:"EBS"},
  {ticker:"RO.SW",name:"Roche Holding",type:"EQUITY",exchange:"EBS"},
  // Asia
  {ticker:"TSM",name:"Taiwan Semiconductor",type:"EQUITY",exchange:"NYQ"},
  {ticker:"7203.T",name:"Toyota Motor",type:"EQUITY",exchange:""},
  {ticker:"6758.T",name:"Sony Group",type:"EQUITY",exchange:""},
  {ticker:"9984.T",name:"SoftBank Group",type:"EQUITY",exchange:""},
  {ticker:"BABA",name:"Alibaba Group",type:"EQUITY",exchange:"NYQ"},
  {ticker:"TCEHY",name:"Tencent Holdings",type:"EQUITY",exchange:""},
  {ticker:"005930.KS",name:"Samsung Electronics",type:"EQUITY",exchange:""},
  // ETF
  {ticker:"SPY",name:"SPDR S&P 500 ETF",type:"ETF",exchange:"NYSEArca"},
  {ticker:"QQQ",name:"Invesco QQQ Trust",type:"ETF",exchange:"NMS"},
  {ticker:"VTI",name:"Vanguard Total Market",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VEA",name:"Vanguard Dev. Markets",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VWO",name:"Vanguard FTSE EM",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EEM",name:"iShares MSCI EM",type:"ETF",exchange:"NYSEArca"},
  {ticker:"GLD",name:"SPDR Gold Shares",type:"ETF",exchange:"NYSEArca"},
  {ticker:"SLV",name:"iShares Silver Trust",type:"ETF",exchange:"NYSEArca"},
  {ticker:"IWM",name:"iShares Russell 2000",type:"ETF",exchange:"NYSEArca"},
  {ticker:"ARKK",name:"ARK Innovation ETF",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLF",name:"Financial Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLK",name:"Technology Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLE",name:"Energy Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLV",name:"Health Care Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"XLI",name:"Industrial Select Sector",type:"ETF",exchange:"NYSEArca"},
  {ticker:"IBIT",name:"iShares Bitcoin Trust",type:"ETF",exchange:"NMS"},
  {ticker:"FBTC",name:"Fidelity Wise Origin Bitcoin",type:"ETF",exchange:"NMS"},
  {ticker:"CW8.PA",name:"Amundi MSCI World",type:"ETF",exchange:"PAR"},
  {ticker:"EWLD.PA",name:"Lyxor MSCI World",type:"ETF",exchange:"PAR"},
  {ticker:"ESE.PA",name:"BNP Paribas Easy S&P 500",type:"ETF",exchange:"PAR"},
  {ticker:"PANX.PA",name:"Amundi Nasdaq-100",type:"ETF",exchange:"PAR"},
  {ticker:"EWJ",name:"iShares MSCI Japan",type:"ETF",exchange:"NYSEArca"},
  {ticker:"FXI",name:"iShares China Large-Cap",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EWG",name:"iShares MSCI Germany",type:"ETF",exchange:"NYSEArca"},
  {ticker:"EWU",name:"iShares MSCI UK",type:"ETF",exchange:"NYSEArca"},
  {ticker:"ACWI",name:"iShares MSCI ACWI",type:"ETF",exchange:"NMS"},
  {ticker:"AGG",name:"iShares Core US Aggregate",type:"ETF",exchange:"NYSEArca"},
  {ticker:"TLT",name:"iShares 20+ Year Treasury",type:"ETF",exchange:"NMS"},
  {ticker:"HYG",name:"iShares iBoxx High Yield",type:"ETF",exchange:"NYSEArca"},
  {ticker:"VNQ",name:"Vanguard Real Estate ETF",type:"ETF",exchange:"NYSEArca"},
  // Crypto
  {ticker:"BTC-USD",name:"Bitcoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ETH-USD",name:"Ethereum",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"SOL-USD",name:"Solana",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"BNB-USD",name:"BNB",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"XRP-USD",name:"XRP",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"DOGE-USD",name:"Dogecoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ADA-USD",name:"Cardano",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"AVAX-USD",name:"Avalanche",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"DOT-USD",name:"Polkadot",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"INJ-USD",name:"Injective",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"LINK-USD",name:"Chainlink",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"UNI7083-USD",name:"Uniswap",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"LTC-USD",name:"Litecoin",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ATOM-USD",name:"Cosmos",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"NEAR-USD",name:"NEAR Protocol",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"ARB-USD",name:"Arbitrum",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"OP-USD",name:"Optimism",type:"CRYPTOCURRENCY",exchange:""},
  {ticker:"SUI20947-USD",name:"Sui",type:"CRYPTOCURRENCY",exchange:""},
  // Indices
  {ticker:"^GSPC",name:"S&P 500",type:"INDEX",exchange:""},
  {ticker:"^NDX",name:"Nasdaq 100",type:"INDEX",exchange:""},
  {ticker:"^DJI",name:"Dow Jones",type:"INDEX",exchange:""},
  {ticker:"^RUT",name:"Russell 2000",type:"INDEX",exchange:""},
  {ticker:"^VIX",name:"VIX Volatility",type:"INDEX",exchange:""},
  {ticker:"^FCHI",name:"CAC 40",type:"INDEX",exchange:""},
  {ticker:"^GDAXI",name:"DAX 40",type:"INDEX",exchange:""},
  {ticker:"^FTSE",name:"FTSE 100",type:"INDEX",exchange:""},
  {ticker:"^N225",name:"Nikkei 225",type:"INDEX",exchange:""},
  {ticker:"^HSI",name:"Hang Seng",type:"INDEX",exchange:""},
  {ticker:"^STOXX50E",name:"Euro Stoxx 50",type:"INDEX",exchange:""},
  {ticker:"^IBEX",name:"IBEX 35",type:"INDEX",exchange:""},
  {ticker:"^AEX",name:"AEX Amsterdam",type:"INDEX",exchange:""},
  {ticker:"^SSMI",name:"SMI Switzerland",type:"INDEX",exchange:""},
];
